server:
  port: 8080
  tomcat:
    uri-encoding: utf-8
spring:
  profiles:
    active: dev

thymeleaf:
  cache: false


# https://baomidou.gitee.io/mybatis-plus-doc/#/install
mybatis-plus:
  # 如果是放在src/main/java目录下 classpath:/com/yourpackage/*/mapper/*Mapper.xml
  # 如果是放在resource目录 classpath:/mapper/*Mapper.xml
  mapper-locations: classpath:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.xrcoding.platform.entity
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    capital-mode: true
    # mybatis 的标志打印取消
    banner: false
  configuration:
    #配置JdbcTypeForNull, oracle数据库必须配置
    jdbc-type-for-null: null



